logging.file: logs/blog.log 
server.port: 8080
server.session.timeout: 10800
server.context-path: /
server.tomcat.uri-encoding: UTF-8
server.tomcat.compression: on

spring.thymeleaf.cache: false  
spring.thymeleaf.mode: LEGACYHTML5


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: 

spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.redis.database: 2
# Redis服务器地址
spring.redis.host: 172.20.9.80
# Redis服务器连接端口
spring.redis.port: 6379  
# Redis服务器连接密码（默认为空）
spring.redis.password:   
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 8  
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: 10000  
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8  
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0  
# 连接超时时间（毫秒）
spring.redis.timeout: 10000  
    